# Generated by Django 5.2.7 on 2025-10-10 01:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('parti', models.CharField(blank=True, max_length=100)),
                ('numero', models.IntegerField(unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='candidats/')),
            ],
            options={
                'verbose_name_plural': 'Candidats',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='CentreVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField()),
                ('commune', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Centres de vote',
            },
        ),
        migrations.CreateModel(
            name='BureauVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('nombre_inscrits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('centre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bureaux', to='elections.centrevote')),
            ],
            options={
                'verbose_name_plural': 'Bureaux de vote',
                'unique_together': {('centre', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Resultat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_voix', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('bureau_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='elections.bureauvote')),
                ('candidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultats', to='elections.candidat')),
            ],
            options={
                'verbose_name_plural': 'Résultats',
                'unique_together': {('candidat', 'bureau_vote')},
            },
        ),
    ]
